version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: soumalya
      POSTGRES_PASSWORD: PkNLm@#2357
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PkNLm@#$2357
      MYSQL_USER: soumalya
      MYSQL_PASSWORD: QsCAzX@#$%24680
    ports:
      - "5000:3306"
    networks:
      - mysql
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge

volumes:
  postgres:
  mysql: