services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: soumalya
      POSTGRES_PASSWORD: PkNLm@#2357
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: