version: '3.3'
services:
  auth-service:
    container_name: auth-service
    build: ./Microservices/AuthenticationService
    depends_on:
      - mysqldb
      - service-discovery
    networks:
      - internal
    restart: on-failure
    
  doctor-service:
    container_name: doctor-service
    build: ./Microservices/DoctorService
    depends_on:
      - mysqldb
      - service-discovery
    networks:
      - internal
    restart: on-failure  
    
  patient-service:
    container_name: patient-service
    build: ./Microservices/PatientService
    depends_on:
      - mysqldb
      - service-discovery
    networks:
      - internal
    restart: on-failure

  service-discovery:
    container_name: service-discovery
    build: ./EurekaServer
    networks:
      - internal
    restart: on-failure
     
  mysqldb:
    container_name: mysql
    image: mysql
    build:
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: PkNLm@#$2357
      MYSQL_USER: soumalya
      MYSQL_PASSWORD: QsCAzX@#$%24680
    ports:
      # for dev only map it to host machine
      # for prod remove the whole port config from here so that it is not accessible from else where
      - "5000:3306"
    networks:
      - internal
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

networks:
  internal:
    driver: bridge
volumes:
  mysql: