version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PkNLm@#$2357
      MYSQL_USER: soumalya
      MYSQL_PASSWORD: QsCAzX@#$%24680
    ports:
      - "5000:3306"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql: