spring:
  profiles:
    active: dev
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/auth/**
        - id: doctor
          uri: lb://DOCTOR
          predicates:
            - Path=/doctor/**
        - id: patient
          uri: lb://PATIENT
          predicates:
            - Path=/patient/**
        - id: appointment
          uri: lb://APPOINTMENT
          predicates:
            - Path=/appointment/**
logging:
  level:
    web: error
    org.springframework.security.we.csrf: debug
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
# okta configuration for API gateway
okta:
  oauth2:
    issuer: https://dev-15970252.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8lyxg5f42w5w9G5d7
    client-secret: smpaVvkJ-1RTksVGlPOmfwsxCbDuQqYYi8KJMQ3m
    scopes: openid, profile, email, offline_access


