spring:
  datasource:
    url: jdbc:mysql://localhost:5000/authentication
    username: soumalya
    password: QsCAzX@#$%24680
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    web: debug