spring:
  profiles:
    active: docker
  application:
    name: AUTHENTICATION
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  retry:
    retryAspectOrder: 3
    instances:
      patientSignupRetry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
      doctorSignupRetry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
      deleteUserRetry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
  circuitbreaker:
#    this is so that in spring aop retry takes more priority than circuit breaker when circuit goes from close to open
#    it retries the request certain number of times before going to open
    circuitBreakerAspectOrder: 2
    instances:
      patientSignupBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      doctorSignupBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      deleteUserBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    rateLimiterAspectOrder: 1
    instances:
      patientServiceRateLimiter:
        limitRefreshPeriod: 10s
        limitForPeriod: 8
        timeoutDuration: 5s
      doctorServiceRateLimiter:
        limitRefreshPeriod: 10s
        limitForPeriod: 8
        timeoutDuration: 8s
      deleteUserRateLimiter:
        limitRefreshPeriod: 10s
        limitForPeriod: 8
        timeoutDuration: 5s
logging:
  level:
    web: error
