spring:
  profiles:
    active: dev
  application:
    name: AUTHENTICATION
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    web: error
