spring:
  datasource:
    url: jdbc:mysql://localhost:5000/patients
    username: soumalya
    password: QsCAzX@#$%24680
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    web: debug